Add check for path to Anaconda in .bash_profile

diff --git a/conda-reset b/conda-reset
--- a/conda-reset
+++ b/conda-reset
@@ -1,7 +1,11 @@
 #!/bin/bash
 
-# grep ~/.bash_profile and find PATH line
-#   fail if the line is not present
+if ! grep -e "export PATH=.*/anaconda2/bin:\$PATH" ~/.bash_profile; then
+  echo "Anaconda path not found in ~/.bash_profile"
+  echo "I'm expecting it to exist, as I am a refresh script"
+  echo "Besides, running Anaconda installer with -b does not add it"
+  exit 1
+fi
 
 rm -rf ~/anaconda2
 bash ~/DML/anaconda/Anaconda2-5.2.0-MacOSX-x86_64.sh -b
