Fail on non-existing packages

diff --git a/prepare-conda-environment-for-ansible-version b/prepare-conda-environment-for-ansible-version
--- a/prepare-conda-environment-for-ansible-version
+++ b/prepare-conda-environment-for-ansible-version
@@ -1,4 +1,5 @@
 #!/bin/bash
+set -e
 
 requested_ansible_version=$1
 
@@ -13,6 +14,10 @@ if [ "${package_url_check_result}" != "200" ]; then
     echo "Ansible version ${requested_ansible_version} not found on PyPI"
     exit 1
 fi
+
+# Still it's not 100% reliable, for example https://pypi.org/project/ansible/1.9
+#   is a valid URL, but there is no such package version and
+#   `pip install ansible==1.9` fails
 
 env_name="ansible-${requested_ansible_version}"
 
